// Code generated by MockGen. DO NOT EDIT.
// Source: matchlist_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/satorunooshie/swipe-shukatu/pkg/domain/model"
)

// MockMatchlistRepository is a mock of MatchlistRepository interface.
type MockMatchlistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMatchlistRepositoryMockRecorder
}

// MockMatchlistRepositoryMockRecorder is the mock recorder for MockMatchlistRepository.
type MockMatchlistRepositoryMockRecorder struct {
	mock *MockMatchlistRepository
}

// NewMockMatchlistRepository creates a new mock instance.
func NewMockMatchlistRepository(ctrl *gomock.Controller) *MockMatchlistRepository {
	mock := &MockMatchlistRepository{ctrl: ctrl}
	mock.recorder = &MockMatchlistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchlistRepository) EXPECT() *MockMatchlistRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockMatchlistRepository) Delete(ctx context.Context, entity *model.Matchlist) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMatchlistRepositoryMockRecorder) Delete(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMatchlistRepository)(nil).Delete), ctx, entity)
}

// Insert mocks base method.
func (m *MockMatchlistRepository) Insert(ctx context.Context, entity *model.Matchlist) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockMatchlistRepositoryMockRecorder) Insert(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockMatchlistRepository)(nil).Insert), ctx, entity)
}

// Select mocks base method.
func (m *MockMatchlistRepository) Select(ctx context.Context, UID string) ([]*model.Matchlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, UID)
	ret0, _ := ret[0].([]*model.Matchlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockMatchlistRepositoryMockRecorder) Select(ctx, UID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockMatchlistRepository)(nil).Select), ctx, UID)
}

// Update mocks base method.
func (m *MockMatchlistRepository) Update(ctx context.Context, entity *model.Matchlist) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMatchlistRepositoryMockRecorder) Update(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMatchlistRepository)(nil).Update), ctx, entity)
}
