// Code generated by MockGen. DO NOT EDIT.
// Source: ltd_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/satorunooshie/swipe-shukatu/pkg/domain/model"
)

// MockLtdRepository is a mock of LtdRepository interface.
type MockLtdRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLtdRepositoryMockRecorder
}

// MockLtdRepositoryMockRecorder is the mock recorder for MockLtdRepository.
type MockLtdRepositoryMockRecorder struct {
	mock *MockLtdRepository
}

// NewMockLtdRepository creates a new mock instance.
func NewMockLtdRepository(ctrl *gomock.Controller) *MockLtdRepository {
	mock := &MockLtdRepository{ctrl: ctrl}
	mock.recorder = &MockLtdRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLtdRepository) EXPECT() *MockLtdRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockLtdRepository) Delete(ctx context.Context, entity *model.Ltd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLtdRepositoryMockRecorder) Delete(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLtdRepository)(nil).Delete), ctx, entity)
}

// Insert mocks base method.
func (m *MockLtdRepository) Insert(ctx context.Context, entity *model.Ltd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockLtdRepositoryMockRecorder) Insert(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockLtdRepository)(nil).Insert), ctx, entity)
}

// Select mocks base method.
func (m *MockLtdRepository) Select(ctx context.Context) ([]*model.Ltd, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx)
	ret0, _ := ret[0].([]*model.Ltd)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockLtdRepositoryMockRecorder) Select(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockLtdRepository)(nil).Select), ctx)
}

// SelectLtdNameByID mocks base method.
func (m *MockLtdRepository) SelectLtdNameByID(ctx context.Context, ltdID int32) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectLtdNameByID", ctx, ltdID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectLtdNameByID indicates an expected call of SelectLtdNameByID.
func (mr *MockLtdRepositoryMockRecorder) SelectLtdNameByID(ctx, ltdID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectLtdNameByID", reflect.TypeOf((*MockLtdRepository)(nil).SelectLtdNameByID), ctx, ltdID)
}

// Update mocks base method.
func (m *MockLtdRepository) Update(ctx context.Context, entity *model.Ltd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLtdRepositoryMockRecorder) Update(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLtdRepository)(nil).Update), ctx, entity)
}
