// Code generated by MockGen. DO NOT EDIT.
// Source: nope_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/satorunooshie/swipe-shukatu/pkg/domain/model"
)

// MockNopeRepository is a mock of NopeRepository interface.
type MockNopeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNopeRepositoryMockRecorder
}

// MockNopeRepositoryMockRecorder is the mock recorder for MockNopeRepository.
type MockNopeRepositoryMockRecorder struct {
	mock *MockNopeRepository
}

// NewMockNopeRepository creates a new mock instance.
func NewMockNopeRepository(ctrl *gomock.Controller) *MockNopeRepository {
	mock := &MockNopeRepository{ctrl: ctrl}
	mock.recorder = &MockNopeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNopeRepository) EXPECT() *MockNopeRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockNopeRepository) Delete(ctx context.Context, entity *model.Nope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNopeRepositoryMockRecorder) Delete(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNopeRepository)(nil).Delete), ctx, entity)
}

// Insert mocks base method.
func (m *MockNopeRepository) Insert(ctx context.Context, entity *model.Nope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockNopeRepositoryMockRecorder) Insert(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockNopeRepository)(nil).Insert), ctx, entity)
}

// Select mocks base method.
func (m *MockNopeRepository) Select(ctx context.Context, UID string) ([]*model.Nope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, UID)
	ret0, _ := ret[0].([]*model.Nope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockNopeRepositoryMockRecorder) Select(ctx, UID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockNopeRepository)(nil).Select), ctx, UID)
}

// Update mocks base method.
func (m *MockNopeRepository) Update(ctx context.Context, entity *model.Nope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNopeRepositoryMockRecorder) Update(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNopeRepository)(nil).Update), ctx, entity)
}
