openapi: 3.0.2
info:
  title: swipe shukatu
  description: |-
    <b>API仕様書</b><br>
    いずれも認証はヘッダーに詰めて行うためURLにidなどは不要
    <p>
    企業のプロフをシェアできるリンク欲しい
    reportは後追い
    中途もスコープから削る
    メッセージリストの絞り込み機能はとりあえず後
    </p>
    <strong>masterデータを持つもの(ex 福利厚生)などは所在地を除いて全てタグで表示する</strong>
  version: 1.0.0
servers:
  - url: http://localhost:8888
tags:
  - name: auth
    description: 認証関連
  - name: user
    description: ユーザ関連
  - name: Ltd
    description: 企業求人関連
  - name: message
    description: メッセージ関連
  - name: match
    description: マッチ関連
  - name: report
    description: 情報が間違って掲載されていた時の報告(追実装)
paths:
  /recruits:
    get:
      tags:
        - Ltd
      summary: 求人を取得するAPI(クエリをつけてカテゴリー別に見れるようにする)
      parameters:
        - name: location
          in: query
          description: 検索条件の会社所在地
          required: true
          schema:
            type: number
        - name: job_type
          in: query
          description: 検索条件の職種
          required: true
          schema:
            type: number
        - name: education_history
          in: query
          description: 検索条件の最終学歴
          required: true
          schema:
            type: number
        - name: benefits
          in: query
          description: 福利厚生
          required: true
          schema:
            type: number
        - name: min_salary
          in: query
          description: 平均年収の最低値(ここは選択肢用意するなら、1~5みたいな感じでも良さそう)
          required: true
          schema:
            type: number
        - name: max_salary
          in: query
          description: 平均年収の最高値
          required: true
          schema:
            type: number
        - name: starting_salary
          in: query
          description: 初任給の最低値
          required: true
          schema:
            type: number
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecruitGetResponse'
  /message/{recruitID}:
    get:
      tags:
        - message
      summary: メッセージを取得するAPI
      description: 過去のメッセージの読み込みはフロントで制御する
      parameters:
        - name: recruitID
          in: path
          description: 求人ID
          required: true
          schema:
            type: number
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageGetResponse'
    post:
      tags:
        - message
      summary: メッセージを送信するAPI
      description: メッセージ送信
      parameters:
        - name: recruitID
          in: path
          description: 求人ID
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessagePostRequest'
        required: true
      responses:
        201:
          description: created
  /message/{recruitID}/{messageID}:
    delete:
      tags:
        - message
      summary: メッセージの送信取り消しをするAPI
      parameters:
        - name: recruitID
          in: path
          description: 求人ID
          required: true
          schema:
            type: number
        - name: messageID
          in: path
          description: メッセージ識別子
          required: true
          schema:
            type: number
      responses:
        204:
          description: no content
  /message/list:
    get:
      tags:
        - match
      summary: メッセージリストの一覧(クエリで絞り込めるようにしてもいいかも ex) superlike or not, IT and real estate)
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageListGetResponse'
  /match/list:
    get:
      tags:
        - match
      summary: Tinderでいう上にあるマッチしたけどメッセージしてない人が一覧で出るやつ
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchListGetResponse'
  /like:
    post:
      tags:
        - Ltd
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LikeRequest'
      responses:
        201:
          description: created
  /superLike:
    post:
      tags:
        - Ltd
      summary: 現在UIに出る文字は最高だが、変えたい
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuperLikeRequest'
      responses:
        201:
          description: created
  /unlike:
    post:
      tags:
        - Ltd
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UnlikeRequest'
      responses:
        201:
          description: created
components:
  schemas:
    RecruitGetResponse:
      type: array
      items:
        $ref: '#/components/schemas/Recruit'
    Recruit:
      type: object
      properties:
        ltd_id:
          type: number
        recruit_id:
          type: number
        name:
          type: string
        profile:
          type: string
        employee_number:
          type: number
        average_age:
          type: number
        job_type:
          type: string
        educational_background:
          type: string
        average_salary:
          type: number
        starting_salary:
          type: number
        image:
          type: string
    MessageGetResponse:
      type: array
      items:
        $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        ltd_id:
          type: number
        recruit_id:
          type: number
        name:
          type: string
        job_type:
          type: string
        content:
          type: string
        image:
          type: string
        created_at:
          type: string
          format: date-time
    MessagePostRequest:
      type: object
      properties:
        message_type:
          type: number
        content:
          type: string
        image:
          type: string
    MessageListGetResponse:
      type: array
      items:
        $ref: '#/components/schemas/MessageList'
    MessageList:
      type: object
      properties:
        ltd_id:
          type: number
        recruit_id:
          type: number
        name:
          type: string
        job_type:
          type: string
        last_message:
          type: string
          description: リストに表示する最後のメッセージ
        created_at:
          type: string
          format: date-time
    MatchListGetResponse:
      type: array
      items:
        $ref: '#/components/schemas/MatchList'
    MatchList:
      type: object
      properties:
        ltd_id:
          type: number
        recruit_id:
          type: number
        name:
          type: string
        job_type:
          type: string
        image:
          type: string
    LikeRequest:
      type: object
      properties:
        recruit_id:
          type: number
    SuperLikeRequest:
      type: object
      properties:
        recruit_id:
          type: number
    UnlikeRequest:
      type: object
      properties:
        recruit_id:
          type: number
    ErrorResponse:
      type: object
      properties:
        error_message:
          type: string
        code:
          type: number
          description: http status code
