version: "3"

volumes:
  mysql-data:

networks:
  swipe-shukatu:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    tty: true
    volumes:
      - ./:/go/src/github.com/satorunooshie/swipe-shukatu
    ports:
      - "8888:8888"
    depends_on:
      - mysql
    networks:
      - swipe-shukatu

  mysql:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: Password!
      MYSQL_DATABASE: swipe_shukatu
      TZ: Asia/Tokyo
    networks:
      - swipe-shukatu

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    environment:
      SWAGGER_JSON: /api/api-document.yml
    volumes:
      - ./api-document.yml:/api/api-document.yml:ro
    ports:
      - 3300:8080

  swagger-api:
    image: stoplight/prism:3
    ports:
      - "10080:4010"
    command: mock -h 0.0.0.0 /api/api-document.yml
    volumes:
      - ./api-document.yml:/api/api-document.yml

  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  client:
    build:
      context: client
    volumes:
      - ./client:/usr/src/app
    ports:
      - '3000:3000'
