// Code generated by MockGen. DO NOT EDIT.
// Source: superlike_handler.go

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSuperLikeHandler is a mock of SuperLikeHandler interface.
type MockSuperLikeHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSuperLikeHandlerMockRecorder
}

// MockSuperLikeHandlerMockRecorder is the mock recorder for MockSuperLikeHandler.
type MockSuperLikeHandlerMockRecorder struct {
	mock *MockSuperLikeHandler
}

// NewMockSuperLikeHandler creates a new mock instance.
func NewMockSuperLikeHandler(ctrl *gomock.Controller) *MockSuperLikeHandler {
	mock := &MockSuperLikeHandler{ctrl: ctrl}
	mock.recorder = &MockSuperLikeHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuperLikeHandler) EXPECT() *MockSuperLikeHandlerMockRecorder {
	return m.recorder
}

// HandleDelete mocks base method.
func (m *MockSuperLikeHandler) HandleDelete() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDelete")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleDelete indicates an expected call of HandleDelete.
func (mr *MockSuperLikeHandlerMockRecorder) HandleDelete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDelete", reflect.TypeOf((*MockSuperLikeHandler)(nil).HandleDelete))
}

// HandleInsert mocks base method.
func (m *MockSuperLikeHandler) HandleInsert() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleInsert")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleInsert indicates an expected call of HandleInsert.
func (mr *MockSuperLikeHandlerMockRecorder) HandleInsert() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleInsert", reflect.TypeOf((*MockSuperLikeHandler)(nil).HandleInsert))
}

// HandleSelect mocks base method.
func (m *MockSuperLikeHandler) HandleSelect() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSelect")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleSelect indicates an expected call of HandleSelect.
func (mr *MockSuperLikeHandlerMockRecorder) HandleSelect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSelect", reflect.TypeOf((*MockSuperLikeHandler)(nil).HandleSelect))
}

// HandleUpdate mocks base method.
func (m *MockSuperLikeHandler) HandleUpdate() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUpdate")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleUpdate indicates an expected call of HandleUpdate.
func (mr *MockSuperLikeHandlerMockRecorder) HandleUpdate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpdate", reflect.TypeOf((*MockSuperLikeHandler)(nil).HandleUpdate))
}
