// Code generated by MockGen. DO NOT EDIT.
// Source: recruit_handler.go

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRecruitHandler is a mock of RecruitHandler interface.
type MockRecruitHandler struct {
	ctrl     *gomock.Controller
	recorder *MockRecruitHandlerMockRecorder
}

// MockRecruitHandlerMockRecorder is the mock recorder for MockRecruitHandler.
type MockRecruitHandlerMockRecorder struct {
	mock *MockRecruitHandler
}

// NewMockRecruitHandler creates a new mock instance.
func NewMockRecruitHandler(ctrl *gomock.Controller) *MockRecruitHandler {
	mock := &MockRecruitHandler{ctrl: ctrl}
	mock.recorder = &MockRecruitHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecruitHandler) EXPECT() *MockRecruitHandlerMockRecorder {
	return m.recorder
}

// HandleDelete mocks base method.
func (m *MockRecruitHandler) HandleDelete() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDelete")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleDelete indicates an expected call of HandleDelete.
func (mr *MockRecruitHandlerMockRecorder) HandleDelete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDelete", reflect.TypeOf((*MockRecruitHandler)(nil).HandleDelete))
}

// HandleInsert mocks base method.
func (m *MockRecruitHandler) HandleInsert() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleInsert")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleInsert indicates an expected call of HandleInsert.
func (mr *MockRecruitHandlerMockRecorder) HandleInsert() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleInsert", reflect.TypeOf((*MockRecruitHandler)(nil).HandleInsert))
}

// HandleSelect mocks base method.
func (m *MockRecruitHandler) HandleSelect() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSelect")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleSelect indicates an expected call of HandleSelect.
func (mr *MockRecruitHandlerMockRecorder) HandleSelect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSelect", reflect.TypeOf((*MockRecruitHandler)(nil).HandleSelect))
}

// HandleUpdate mocks base method.
func (m *MockRecruitHandler) HandleUpdate() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUpdate")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleUpdate indicates an expected call of HandleUpdate.
func (mr *MockRecruitHandlerMockRecorder) HandleUpdate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpdate", reflect.TypeOf((*MockRecruitHandler)(nil).HandleUpdate))
}
