// Code generated by MockGen. DO NOT EDIT.
// Source: like_handler.go

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLikeHandler is a mock of LikeHandler interface.
type MockLikeHandler struct {
	ctrl     *gomock.Controller
	recorder *MockLikeHandlerMockRecorder
}

// MockLikeHandlerMockRecorder is the mock recorder for MockLikeHandler.
type MockLikeHandlerMockRecorder struct {
	mock *MockLikeHandler
}

// NewMockLikeHandler creates a new mock instance.
func NewMockLikeHandler(ctrl *gomock.Controller) *MockLikeHandler {
	mock := &MockLikeHandler{ctrl: ctrl}
	mock.recorder = &MockLikeHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeHandler) EXPECT() *MockLikeHandlerMockRecorder {
	return m.recorder
}

// HandleDelete mocks base method.
func (m *MockLikeHandler) HandleDelete() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDelete")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleDelete indicates an expected call of HandleDelete.
func (mr *MockLikeHandlerMockRecorder) HandleDelete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDelete", reflect.TypeOf((*MockLikeHandler)(nil).HandleDelete))
}

// HandleInsert mocks base method.
func (m *MockLikeHandler) HandleInsert() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleInsert")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleInsert indicates an expected call of HandleInsert.
func (mr *MockLikeHandlerMockRecorder) HandleInsert() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleInsert", reflect.TypeOf((*MockLikeHandler)(nil).HandleInsert))
}

// HandleSelect mocks base method.
func (m *MockLikeHandler) HandleSelect() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSelect")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleSelect indicates an expected call of HandleSelect.
func (mr *MockLikeHandlerMockRecorder) HandleSelect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSelect", reflect.TypeOf((*MockLikeHandler)(nil).HandleSelect))
}

// HandleUpdate mocks base method.
func (m *MockLikeHandler) HandleUpdate() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUpdate")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleUpdate indicates an expected call of HandleUpdate.
func (mr *MockLikeHandlerMockRecorder) HandleUpdate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpdate", reflect.TypeOf((*MockLikeHandler)(nil).HandleUpdate))
}
