// Code generated by MockGen. DO NOT EDIT.
// Source: ltd_handler.go

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLtdHandler is a mock of LtdHandler interface.
type MockLtdHandler struct {
	ctrl     *gomock.Controller
	recorder *MockLtdHandlerMockRecorder
}

// MockLtdHandlerMockRecorder is the mock recorder for MockLtdHandler.
type MockLtdHandlerMockRecorder struct {
	mock *MockLtdHandler
}

// NewMockLtdHandler creates a new mock instance.
func NewMockLtdHandler(ctrl *gomock.Controller) *MockLtdHandler {
	mock := &MockLtdHandler{ctrl: ctrl}
	mock.recorder = &MockLtdHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLtdHandler) EXPECT() *MockLtdHandlerMockRecorder {
	return m.recorder
}

// HandleDelete mocks base method.
func (m *MockLtdHandler) HandleDelete() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDelete")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleDelete indicates an expected call of HandleDelete.
func (mr *MockLtdHandlerMockRecorder) HandleDelete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDelete", reflect.TypeOf((*MockLtdHandler)(nil).HandleDelete))
}

// HandleInsert mocks base method.
func (m *MockLtdHandler) HandleInsert() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleInsert")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleInsert indicates an expected call of HandleInsert.
func (mr *MockLtdHandlerMockRecorder) HandleInsert() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleInsert", reflect.TypeOf((*MockLtdHandler)(nil).HandleInsert))
}

// HandleSelect mocks base method.
func (m *MockLtdHandler) HandleSelect() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSelect")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleSelect indicates an expected call of HandleSelect.
func (mr *MockLtdHandlerMockRecorder) HandleSelect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSelect", reflect.TypeOf((*MockLtdHandler)(nil).HandleSelect))
}

// HandleUpdate mocks base method.
func (m *MockLtdHandler) HandleUpdate() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUpdate")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// HandleUpdate indicates an expected call of HandleUpdate.
func (mr *MockLtdHandlerMockRecorder) HandleUpdate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpdate", reflect.TypeOf((*MockLtdHandler)(nil).HandleUpdate))
}
