// Code generated by MockGen. DO NOT EDIT.
// Source: matchlist_usecase.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/satorunooshie/swipe-shukatu/pkg/domain/model"
)

// MockMatchlistUseCase is a mock of MatchlistUseCase interface.
type MockMatchlistUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockMatchlistUseCaseMockRecorder
}

// MockMatchlistUseCaseMockRecorder is the mock recorder for MockMatchlistUseCase.
type MockMatchlistUseCaseMockRecorder struct {
	mock *MockMatchlistUseCase
}

// NewMockMatchlistUseCase creates a new mock instance.
func NewMockMatchlistUseCase(ctrl *gomock.Controller) *MockMatchlistUseCase {
	mock := &MockMatchlistUseCase{ctrl: ctrl}
	mock.recorder = &MockMatchlistUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchlistUseCase) EXPECT() *MockMatchlistUseCaseMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockMatchlistUseCase) Delete(ctx context.Context, entity *model.Matchlist) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMatchlistUseCaseMockRecorder) Delete(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMatchlistUseCase)(nil).Delete), ctx, entity)
}

// Insert mocks base method.
func (m *MockMatchlistUseCase) Insert(ctx context.Context, entity *model.Matchlist) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockMatchlistUseCaseMockRecorder) Insert(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockMatchlistUseCase)(nil).Insert), ctx, entity)
}

// Select mocks base method.
func (m *MockMatchlistUseCase) Select(ctx context.Context, UID string) ([]*model.Matchlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, UID)
	ret0, _ := ret[0].([]*model.Matchlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockMatchlistUseCaseMockRecorder) Select(ctx, UID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockMatchlistUseCase)(nil).Select), ctx, UID)
}

// Update mocks base method.
func (m *MockMatchlistUseCase) Update(ctx context.Context, entity *model.Matchlist) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMatchlistUseCaseMockRecorder) Update(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMatchlistUseCase)(nil).Update), ctx, entity)
}
