// Code generated by MockGen. DO NOT EDIT.
// Source: recruit_usecase.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/satorunooshie/swipe-shukatu/pkg/domain/model"
)

// MockRecruitUseCase is a mock of RecruitUseCase interface.
type MockRecruitUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRecruitUseCaseMockRecorder
}

// MockRecruitUseCaseMockRecorder is the mock recorder for MockRecruitUseCase.
type MockRecruitUseCaseMockRecorder struct {
	mock *MockRecruitUseCase
}

// NewMockRecruitUseCase creates a new mock instance.
func NewMockRecruitUseCase(ctrl *gomock.Controller) *MockRecruitUseCase {
	mock := &MockRecruitUseCase{ctrl: ctrl}
	mock.recorder = &MockRecruitUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecruitUseCase) EXPECT() *MockRecruitUseCaseMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRecruitUseCase) Delete(ctx context.Context, entity *model.Recruit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRecruitUseCaseMockRecorder) Delete(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecruitUseCase)(nil).Delete), ctx, entity)
}

// Insert mocks base method.
func (m *MockRecruitUseCase) Insert(ctx context.Context, entity *model.Recruit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockRecruitUseCaseMockRecorder) Insert(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockRecruitUseCase)(nil).Insert), ctx, entity)
}

// Select mocks base method.
func (m *MockRecruitUseCase) Select(ctx context.Context) ([]*model.Recruit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx)
	ret0, _ := ret[0].([]*model.Recruit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockRecruitUseCaseMockRecorder) Select(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockRecruitUseCase)(nil).Select), ctx)
}

// Update mocks base method.
func (m *MockRecruitUseCase) Update(ctx context.Context, entity *model.Recruit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRecruitUseCaseMockRecorder) Update(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecruitUseCase)(nil).Update), ctx, entity)
}
