// Code generated by MockGen. DO NOT EDIT.
// Source: ltd_usecase.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/satorunooshie/swipe-shukatu/pkg/domain/model"
)

// MockLtdUseCase is a mock of LtdUseCase interface.
type MockLtdUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockLtdUseCaseMockRecorder
}

// MockLtdUseCaseMockRecorder is the mock recorder for MockLtdUseCase.
type MockLtdUseCaseMockRecorder struct {
	mock *MockLtdUseCase
}

// NewMockLtdUseCase creates a new mock instance.
func NewMockLtdUseCase(ctrl *gomock.Controller) *MockLtdUseCase {
	mock := &MockLtdUseCase{ctrl: ctrl}
	mock.recorder = &MockLtdUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLtdUseCase) EXPECT() *MockLtdUseCaseMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockLtdUseCase) Delete(ctx context.Context, entity *model.Ltd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLtdUseCaseMockRecorder) Delete(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLtdUseCase)(nil).Delete), ctx, entity)
}

// Insert mocks base method.
func (m *MockLtdUseCase) Insert(ctx context.Context, entity *model.Ltd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockLtdUseCaseMockRecorder) Insert(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockLtdUseCase)(nil).Insert), ctx, entity)
}

// Select mocks base method.
func (m *MockLtdUseCase) Select(ctx context.Context) ([]*model.Ltd, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx)
	ret0, _ := ret[0].([]*model.Ltd)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockLtdUseCaseMockRecorder) Select(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockLtdUseCase)(nil).Select), ctx)
}

// Update mocks base method.
func (m *MockLtdUseCase) Update(ctx context.Context, entity *model.Ltd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLtdUseCaseMockRecorder) Update(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLtdUseCase)(nil).Update), ctx, entity)
}
