// Code generated by MockGen. DO NOT EDIT.
// Source: job_usecase.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/satorunooshie/swipe-shukatu/pkg/domain/model"
)

// MockJobUseCase is a mock of JobUseCase interface.
type MockJobUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockJobUseCaseMockRecorder
}

// MockJobUseCaseMockRecorder is the mock recorder for MockJobUseCase.
type MockJobUseCaseMockRecorder struct {
	mock *MockJobUseCase
}

// NewMockJobUseCase creates a new mock instance.
func NewMockJobUseCase(ctrl *gomock.Controller) *MockJobUseCase {
	mock := &MockJobUseCase{ctrl: ctrl}
	mock.recorder = &MockJobUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobUseCase) EXPECT() *MockJobUseCaseMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockJobUseCase) Delete(ctx context.Context, entity *model.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockJobUseCaseMockRecorder) Delete(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockJobUseCase)(nil).Delete), ctx, entity)
}

// Insert mocks base method.
func (m *MockJobUseCase) Insert(ctx context.Context, entity *model.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockJobUseCaseMockRecorder) Insert(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockJobUseCase)(nil).Insert), ctx, entity)
}

// Select mocks base method.
func (m *MockJobUseCase) Select(ctx context.Context) ([]*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx)
	ret0, _ := ret[0].([]*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockJobUseCaseMockRecorder) Select(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockJobUseCase)(nil).Select), ctx)
}

// Update mocks base method.
func (m *MockJobUseCase) Update(ctx context.Context, entity *model.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockJobUseCaseMockRecorder) Update(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockJobUseCase)(nil).Update), ctx, entity)
}
