// Code generated by MockGen. DO NOT EDIT.
// Source: nope_usecase.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/satorunooshie/swipe-shukatu/pkg/domain/model"
)

// MockNopeUseCase is a mock of NopeUseCase interface.
type MockNopeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockNopeUseCaseMockRecorder
}

// MockNopeUseCaseMockRecorder is the mock recorder for MockNopeUseCase.
type MockNopeUseCaseMockRecorder struct {
	mock *MockNopeUseCase
}

// NewMockNopeUseCase creates a new mock instance.
func NewMockNopeUseCase(ctrl *gomock.Controller) *MockNopeUseCase {
	mock := &MockNopeUseCase{ctrl: ctrl}
	mock.recorder = &MockNopeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNopeUseCase) EXPECT() *MockNopeUseCaseMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockNopeUseCase) Delete(ctx context.Context, entity *model.Nope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNopeUseCaseMockRecorder) Delete(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNopeUseCase)(nil).Delete), ctx, entity)
}

// Insert mocks base method.
func (m *MockNopeUseCase) Insert(ctx context.Context, entity *model.Nope, UID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, entity, UID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockNopeUseCaseMockRecorder) Insert(ctx, entity, UID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockNopeUseCase)(nil).Insert), ctx, entity, UID)
}

// Select mocks base method.
func (m *MockNopeUseCase) Select(ctx context.Context, UID string) ([]*model.Nope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, UID)
	ret0, _ := ret[0].([]*model.Nope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockNopeUseCaseMockRecorder) Select(ctx, UID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockNopeUseCase)(nil).Select), ctx, UID)
}

// Update mocks base method.
func (m *MockNopeUseCase) Update(ctx context.Context, entity *model.Nope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNopeUseCaseMockRecorder) Update(ctx, entity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNopeUseCase)(nil).Update), ctx, entity)
}
