name: test_and_lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go: ["1.16", "1.15"]
        os: [ubuntu-latest, macos-latest]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set build variables
        run: |
          echo "GO111MODULE=on" >> $GITHUB_ENV
      - name: Get dependencies
        run: |
          go mod download
      - name: Install tools
        run: make deps

      - name: Run test
        run: richgo test ./... -v -count=1 -cover

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1

      - name: Install sleuth
        run: go get github.com/sivchari/sleuth

      - name: Run sleuth
        run: go vet -vettool=`which sleuth` ./...
